Repository zkoss/zk, pull requests merged in 2022-05, with the labels that each got.

#2761 Upgrade to Chromium 101.0.4950.0
  zktest/pom.xml
  zktest/test/java/org/zkoss/zktest/zats/ChromiumHeadlessDriver.java
Labels: WIP, need-config.properties, need-release-note

#2771 upgrade node version to v16.14.2
  zk-parent/pom.xml
Labels: need-config.properties, need-release-note

#2770 ZK-5110: ZKWebSocket cause NPE on reconnect if session has been destr…
  zk/src/org/zkoss/zk/ui/http/ZKWebSocket.java
  zkdoc/release-note
Labels: need-config.properties

#2777 fix javadoc and jsdoc
  zcommon/src/org/zkoss/json/JSONArray.java
  zcommon/src/org/zkoss/json/JSONAware.java
  zcommon/src/org/zkoss/json/JSONObject.java
  zcommon/src/org/zkoss/json/JSONValue.java
  zcommon/src/org/zkoss/json/parser/ContainerFactory.java
  zcommon/src/org/zkoss/json/parser/JSONParser.java
  zcommon/src/org/zkoss/json/parser/ParseException.java
  zcommon/src/org/zkoss/json/parser/Yytoken.java
  zcommon/src/org/zkoss/lang/Exceptions.java
  zcommon/src/org/zkoss/util/FastReadArray.java
  zcommon/src/org/zkoss/util/Maps.java
  zk/src/archive/web/js/zk/dom.ts
  zk/src/archive/web/js/zk/drag.ts
  zk/src/archive/web/js/zk/widget.ts
  zk/src/archive/web/js/zk/zk.ts
  zk/src/org/zkoss/zk/ui/Execution.java
  zk/src/org/zkoss/zk/ui/sys/PageCtrl.java
  zk/src/org/zkoss/zk/ui/util/ConfigParser.java
  zkbind/src/org/zkoss/bind/ValidationContext.java
  zkbind/src/org/zkoss/bind/sys/Binding.java
  zkbind/src/org/zkoss/bind/sys/PropertyBinding.java
  zkbind/src/org/zkoss/bind/sys/SaveBinding.java
  zkplus-legacy/src/org/zkoss/zkplus/databind/SelectedItemConverter.java
  zkplus/src/org/zkoss/zkplus/cdi/CDIUtil.java
  zul/src/archive/web/js/zul/db/Datebox.js
  zul/src/org/zkoss/zul/Grid.java
  zul/src/org/zkoss/zul/Listbox.java
  zul/src/org/zkoss/zul/Script.java
  zul/src/org/zkoss/zul/SimpleListModel.java
  zul/src/org/zkoss/zul/Tree.java
  zul/src/org/zkoss/zul/impl/InputElement.java
  zul/src/org/zkoss/zul/impl/NumberInputElement.java
  zweb/src/org/zkoss/web/fn/ServletFns.java
  zweb/src/org/zkoss/web/servlet/Servlets.java
  zweb/src/org/zkoss/web/servlet/dsp/Interpreter.java
  zweb/src/org/zkoss/web/theme/ThemeRegistry.java
Labels: need-config.properties, need-release-note

#2778 Add release date in the release-note
  zkdoc/release-note
Labels: need-config.properties

#2782 Replace @zk with relative path
  tsconfig.json
  webpack.config.js
  zk/.eslintrc.json
  zk/src/main/resources/web/js/zk/anima.ts
  zk/src/main/resources/web/js/zk/au.ts
  zk/src/main/resources/web/js/zk/bookmark.ts
  zk/src/main/resources/web/js/zk/dateImpl.ts
  zk/src/main/resources/web/js/zk/dom.ts
  zk/src/main/resources/web/js/zk/domgecko.ts
  zk/src/main/resources/web/js/zk/domopera.ts
  zk/src/main/resources/web/js/zk/domsafari.ts
  zk/src/main/resources/web/js/zk/domtouch.ts
  zk/src/main/resources/web/js/zk/drag.ts
  zk/src/main/resources/web/js/zk/effect.ts
  zk/src/main/resources/web/js/zk/evt.ts
  zk/src/main/resources/web/js/zk/flex.ts
  zk/src/main/resources/web/js/zk/global.d.ts
  zk/src/main/resources/web/js/zk/historystate.ts
  zk/src/main/resources/web/js/zk/index.ts
  zk/src/main/resources/web/js/zk/math.ts
  zk/src/main/resources/web/js/zk/mount.ts
  zk/src/main/resources/web/js/zk/pkg.ts
  zk/src/main/resources/web/js/zk/utl.ts
  zk/src/main/resources/web/js/zk/widget.ts
  zk/src/main/resources/web/js/zk/zk.ts
  zk/src/main/resources/web/js/zk/zswipe.ts
  zk/tsconfig.json
Labels: need-config.properties, need-release-note
